[package]
name = "adapter-wayland"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "y2skk-wayland"
path = "src/main.rs"

[dependencies]
skk-ipc            = { path = "../skk-ipc" }
anyhow             = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
zbus               = { workspace = true }
wayland-client   = "0.31.14"
wayland-protocols = { version = "0.32.12", features = ["client", "unstable"] }
xkbcommon = "0.9.0"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
rustix = { version = "1.1.4", features = ["fs", "mm", "event", "pipe"] }
fontdue = "0.9.3"
